name: vocacional_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  quickalert: ^1.0.3
  animated_text_kit: ^4.2.2
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.6
  path: ^1.9.0
  crypto: ^3.0.7
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.2
  intl: ^0.20.2
  confetti: ^0.7.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#1976D2"

flutter:
  uses-material-design: true
  assets:
    - assets/student.png
    - assets/ayuda.png
    - assets/images/logo.png